- hosts: all
  become: true
  tasks:
    - name: Delete old deployment
      kubernetes.core.k8s:
        kubeconfig: /home/ubuntu/.kube/config  # Specify your kubeconfig
        state: absent
        definition: 
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: elzarafa  # Update with your deployment name
            namespace: default  # Specify namespace if not default

    - name: Delete old service
      kubernetes.core.k8s:
        kubeconfig: /home/ubuntu/.kube/config  # Specify your kubeconfig
        state: absent
        definition: 
          apiVersion: v1
          kind: Service
          metadata:
            name: ElZarafa  # Update with your service name
            namespace: default  # Specify namespace if not default

    - name: Create new deployment
      kubernetes.core.k8s:
        kubeconfig: /home/ubuntu/.kube/config  # Specify your kubeconfig
        state: present
        src: /home/ubuntu/Deployment.yml  # Path to your existing Deployment YAML file
        namespace: default

    - name: Create new service
      kubernetes.core.k8s:
        kubeconfig: /home/ubuntu/.kube/config  # Specify your kubeconfig
        state: present
        src: /home/ubuntu/Service.yml  # Path to your existing Service YAML file
        namespace: default
