apiVersion: apps/v1
kind: Deployment
metadata:
  name: elzarafa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elzarafa
  template:
    metadata:
      labels:
        app: elzarafa
    spec:
      containers:
        - name: elzarafa
          image: elzarafa/pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
