kind: Service                             
apiVersion: v1
metadata:
  name: elzarafa
  labels:
    app: elzarafa
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: elzarafa                    
  type: LoadBalancer                   